name: "Run Maven Build"
description: "Build and test a Maven Spring Boot application"

inputs:
  java-version:
    required: true
    type: string

runs:
  using: "composite"
  steps:

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}

    - name: Build with Maven
      run: mvn -B clean install
      shell: bash

    - name: Run tests
      run: mvn test
      shell: bash
