name: "Java CI"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: call composite action to setup java with 21 as input ,build and run tests
        uses: ./.github/actions
        with:
          java-version: "21"
